### ISSUE TITLE
Trouble installing GDAL through pip

### ISSUE THREAD

**Issue by kramduckner** [avaframe/FlowPy#1]
Hey guys!
Really excited about the work you've done for this. Thanks a million.

I'm trying to follow the installation instructions and getting an error after running pip install -r requirements.txt. I'm trying to install on Ubuntu 20.04. Would be happy to expand on my environment if it's relevant! Here's the output:
Collecting GDAL
  Downloading GDAL-3.5.0.3.tar.gz (745 kB)
     |████████████████████████████████| 745 kB 22.8 MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-usbm56lp/GDAL/setup.py'"'"'; __file__='"'"'/tmp/pip-install-usbm56lp/GDAL/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-usbm56lp/GDAL/pip-egg-info
         cwd: /tmp/pip-install-usbm56lp/GDAL/
    Complete output (79 lines):
    WARNING: numpy not available!  Array support will not be enabled
    running egg_info
    creating /tmp/pip-install-usbm56lp/GDAL/pip-egg-info/GDAL.egg-info
    writing /tmp/pip-install-usbm56lp/GDAL/pip-egg-info/GDAL.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-usbm56lp/GDAL/pip-egg-info/GDAL.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-install-usbm56lp/GDAL/pip-egg-info/GDAL.egg-info/requires.txt
    writing top-level names to /tmp/pip-install-usbm56lp/GDAL/pip-egg-info/GDAL.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-usbm56lp/GDAL/pip-egg-info/GDAL.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "/tmp/pip-install-usbm56lp/GDAL/setup.py", line 80, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-install-usbm56lp/GDAL/setup.py", line 181, in get_gdal_config
        return fetch_config(option, gdal_config=self.gdal_config)
      File "/tmp/pip-install-usbm56lp/GDAL/setup.py", line 83, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-usbm56lp/GDAL/setup.py", line 343, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 297, in run
        self.find_sources()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 304, in find_sources
        mm.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 535, in run
        self.add_defaults()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 571, in add_defaults
        sdist.add_defaults(self)
      File "/usr/lib/python3.8/distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/usr/lib/python3.8/distutils/command/sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/lib/python3.8/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-install-usbm56lp/GDAL/setup.py", line 248, in finalize_options
        gdaldir = self.get_gdal_config('prefix')
      File "/tmp/pip-install-usbm56lp/GDAL/setup.py", line 187, in get_gdal_config
        raise gdal_config_error(traceback_string + '\n' + msg)
    __main__.gdal_config_error: Traceback (most recent call last):
      File "/tmp/pip-install-usbm56lp/GDAL/setup.py", line 80, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-install-usbm56lp/GDAL/setup.py", line 181, in get_gdal_config
        return fetch_config(option, gdal_config=self.gdal_config)
      File "/tmp/pip-install-usbm56lp/GDAL/setup.py", line 83, in fetch_config
        raise gdal_config_error(e)
    gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'

    Could not find gdal-config. Make sure you have installed the GDAL native library and development headers.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

It looks like the native headers and libgdal have to be installed before running the pip installation command, according to the [gdal docs](https://pypi.org/project/GDAL/). 

I'd be happy to submit a PR for the readme to include this! Just let me know.

**Comment by Iceman-bfw** [comment]
Hi Mark, 

thx for your support. If you have any solution for this that works on Windows and Linux, pls feel free to submit the PR.
I had always troubles with installing gdal and rasterio via pip that works on both OS, so i did it most of the times by downloading the wheel and installing it.

Or we focus on Ubuntu with the requirments.txt and do it with the wheel files on windows... I'm flexible there ;)

Best Regards,
Michael

**Comment by kramduckner** [comment]
You got it! I think I can get some quick information on mac/linux (if you're still interested in mac os instructions), but I'll have to spend some extra time working with windows, but I'll try to do that sometime soon. If I find myself too busy, I'll close the issue to keep the repo clean : )
